id: I9F8439FB
legacy_id: P000498
ocr_import_info:
  bdrc_scan_id: W8LS20189
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T13:45:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:39:46.989948+00:00'
last_modified: 2022-09-04 12:39:52.159496
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS20189
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS20189
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲག་པོ་ཡེ་ཤེས་རབ་འབར་གྱི་བསྙེན་ཡིག་དམ་པའི་ཞལ་ལུང་།
  author: ཞེ་ཆེན་དབོན་སྤྲུལ་འགྱུར་མེད་མཐུ་སྟོབས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.6969779881877157
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I8LS20191:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS20191
      total_pages: 70
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS20191.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6969779881877157
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
